# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: nginx
#   namespace: argocd
# spec:
#   project: gaudi-cloud
#   destination:
#     namespace: nginx
#     server: https://kubernetes.default.svc
#   source:
#     repoURL: git@github.com:gaudi-organization/gaudi-cloud.git
#     path: k8s/manifests/gcp/services/nginx/gaudi-prd
#     targetRevision: main
#   syncPolicy:
#     syncOptions:
#       - CreateNamespace=true
#     automated:
#       selfHeal: true
#       prune: true
