apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/env: prd
      app.kubernetes.io/owner: backend
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/name: nginx
    includeTemplates: true
namespace: nginx
resources:
  - ./deployment.yaml
  - ./hpa.yaml
  - ./ingress.yaml
  - ./namespace.yaml
  - ./service.yaml
