apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "nginx-backend-config"}'
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: nginx-pod
