apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/env: prd
      app.kubernetes.io/owner: cloud-platform
      app.kubernetes.io/managed-by: argocd
    includeTemplates: true
resources:
  - ./namespace.yaml
namespace: external-secrets-operator
helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    releaseName: external-secrets
    version: 0.10.4
    valuesFile: ./values.yaml
    namespace: external-secrets-operator
    includeCRDs: true
