apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gaudi-backend
  namespace: argocd
spec:
  project: gaudi
  destination:
    namespace: gaudi-backend
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:gaudi-organization/gaudi-backend.git
    path: charts/backend
    targetRevision: main
    helm:
      valueFiles:
        - values/prd.yaml
        - values/prd-image-tag.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
