apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/env: prd
      app.kubernetes.io/owner: cloud-platform
      app.kubernetes.io/managed-by: argocd
    includeTemplates: true
resources:
  - ./namespace.yaml
namespace: cert-manager
helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    releaseName: cert-manager
    version: 1.16.0
    valuesFile: ./values.yaml
    namespace: cert-manager
    includeCRDs: true
