apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: gaudi-cloud
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:gaudi-organization/gaudi-cloud.git
    path: k8s/manifests/gcp/platform/kube-prometheus-stack/gaudi-prd
    targetRevision: main
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
      - PruneLast=false
    automated:
      selfHeal: true
      prune: true
