apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/env: prd
      app.kubernetes.io/owner: cloud-platform
      app.kubernetes.io/managed-by: argocd
    includeTemplates: true
resources:
  - ./certificates.yaml
