apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/env: prd
      app.kubernetes.io/owner: cloud-platform
      app.kubernetes.io/managed-by: argocd
    includeTemplates: true
namespace: kube-system
helmCharts:
  - name: metrics-server
    repo: https://kubernetes-sigs.github.io/metrics-server
    releaseName: metrics-server
    version: 3.12.1
    valuesFile: ./values.yaml
    namespace: kube-system
    includeCRDs: true
