apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/env: prd
      app.kubernetes.io/owner: cloud-platform
      app.kubernetes.io/managed-by: argocd
    includeTemplates: true
resources:
  - ./namespace.yaml
namespace: external-dns
helmCharts:
  - name: external-dns
    repo: https://kubernetes-sigs.github.io/external-dns/
    releaseName: external-dns
    version: 1.15.0
    valuesFile: ./values.yaml
    namespace: external-dns
    includeCRDs: true
