# apiVersion: cloud.google.com/v1
# kind: BackendConfig
# metadata:
#   name: argocd-server
#   namespace: argocd
# spec:
#   timeoutSec: 30
#   connectionDraining:
#     drainingTimeoutSec: 30
#   healthCheck:
#     checkIntervalSec: 10
#     timeoutSec: 5
#     unhealthyThreshold: 3
#     healthyThreshold: 2
#     type: HTTP
#     requestPath: "/"
#   iap:
#     enabled: false
