name: Go

on:
  push:
    branches:
      - "main"
      - "develop"
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"
  pull_request:
    branches:
      - "main"
      - "develop"
      - "feature/**"
      - "hotfix/**"
      - "**"
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.1"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Test code
        run: |
          cd ../../pkg/api
          go test -v ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.1"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd ../../pkg/api
          go build -v ./main.go
